package _const

const RENTAL_ORDER_PENDING = "PENDING"
const RENTAL_ORDER_VOID = "VOID"
const RENTAL_ORDER_CANCELED = "CANCELED"
const RENTAL_ORDER_COMPLETED = "COMPLETED"
const RENTAL_ORDER_TRANSFERRED = "TRANSFERRED"
const RENTAL_ORDER_TERMINATED = "TERMINATED"
const RENTAL_ORDER_DONATED = "DONATED"
const RENTAL_ORDER_EXTEND = "EXTEND"
const RENTAL_ORDER_REFUND = "REFUND"

//order TYPE
const RENTAL_ORDER_TYPE_RENT = "Rent"
const RENTAL_ORDER_TYPE_EXTEND = "Extend"
const RENTAL_ORDER_TYPE_TRANSFER = "Transfer"
const RENTAL_ORDER_TYPE_PENALTY = "Penalty"
const RENTAL_ORDER_TYPE_DEPOSIT = "Deposit"

//reference TYPE
const REFERENCE_TRANSFER = "TRANSFER"
const REFERENCE_EXTEND = "EXTEND"
const REFERENCE_PENALTY = "PENALTY"

//const REFERENCE_MOVE = "MOVE"

const RENTAL_ORDER_ITEM_TYPE_STORAGE = "STORAGE"
