package _const

const SCHEDULE_ACTIVE = "ACTIVE"
const SCHEDULE_INACTIVE = "INACTIVE"
const SCHEDULE_CANCEL = "CANCEL"
const SCHEDULE_INVALID = "INVALID"
const SCHEDULE_COMPLETE = "COMPLETE"

const SCHEDULE_STORAGE_DAILY_EXPIRE = "SCHEDULE_STORAGE_DAILY_EXPIRE"
const SCHEDULE_STORAGE_RENT_EXTEND = "SCHEDULE_STORAGE_RENT_EXTEND"
const SCHEDULE_STORAGE_RENT = "SCHEDULE_STORAGE_RENT"
const SCHEDULE_STORAGE_EXPIRE = "SCHEDULE_STORAGE_EXPIRE"
const SCHEDULE_STORAGE_TRANSFER_IN = "SCHEDULE_STORAGE_TRANSFER_IN"
const SCHEDULE_STORAGE_TRANSFER_OUT = "SCHEDULE_STORAGE_TRANSFER_OUT"
const SCHEDULE_STORAGE_TERMINATE = "SCHEDULE_STORAGE_TERMINATE"
