package _const

const STORAGE_RENT = "RENT"
const STORAGE_EXPIRED = "EXPIRED"
const STORAGE_AVAILABLE = "AVAILABLE"
const STORAGE_DISABLE = "DISABLE"
const STORAGE_PENDING = "PENDING"

const NA = "N/A"

//rent type
const RENT_TYPE_YEAR = "YEAR"
const RENT_TYPE_MONTH = "MONTH"
const RENT_TYPE_DAY = "DAY"

//storage type
const STORAGE_TYPE_PRIVATE_STORAGE = "PRIVATE_STORAGE"
const STORAGE_TYPE_STORAGE_RACK = "STORAGE_RACK"
