package pdf

import (
	"testing"
	"time"
)

func Test_PDF(t *testing.T) {
	orderReceipt := GetOrderTemplate("EN")
	orderReceipt.SetHeader(&HeaderInfo{
		CompanyName: "Boxapp ",
		Address:     "ggduqwhdbwqdnhwqdnoqwdwqdwqmdjwqmdwqoindwqhodmqwdwqdwqdwqbdwqbdwqbdbbkwqdqwdgwqiqwdwqdwdqwd61872980uehfg7831yh3fncfi",
		Email:       "4655667889ijftyuijjb@fyuijbvr76t7889jjh.com",
		Phone:       "(852)43345566778789895645",
	})
	orderReceipt.SetFooter("Order System Provided by JOJORENT 出租王 boxapp.com.hk")

	orderReceipt.SetOrderNumber("34567898546567hHJB")
	orderReceipt.SetCustomerInfo(CustomerInfo{
		Name:  "Lokman",
		Phone: "345687989",
		Email: "56789@&(986",
	})
	orderReceipt.SetTable([]string{"BRANCH NAME", "STORAGE NUMBER", "DETAILS", "RENT PERIOD", "DATE (START TO END)", "TOTAL AMOUNT"},
		[]string{"565", "2", "remarks", "1 YEAR",
			"2022-01-30\nto\n2023-01-29", "$100"})
	orderReceipt.SetOrderInfo(OrderInfo{
		Date:   time.Now(),
		Status: "COMPLETED",
	})
	orderReceipt.SetRemarks(`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam congue condimentum neque, sit amet vulputate odio molestie ut. Sed rutrum enim vitae laoreet viverra. Nullam non tristique tortor. Mauris lacinia efficitur pretium. Quisque mattis dignissim erat, id faucibus eros viverra in. Fusce ut nibh ac sem tincidunt tincidunt. Etiam varius, eros eget accumsan gravida, ipsum nulla aliquam erat, ac euismod risus mi ac odio. Praesent nec iaculis nibh, ac dapibus purus. Morbi nulla felis, gravida vel fringilla sed, rhoncus non tortor. In turpis enim, porttitor sed congue id, suscipit id libero. Praesent convallis orci varius nisi maximus gravida. Sed a ante vel orci accumsan sollicitudin non in mi. Vivamus sem urna, imperdiet eget lorem nec, faucibus vestibulum lorem. Phasellus facilisis tellus et felis faucibus, a maximus ipsum sollicitudin. Suspendisse potenti.

Cras bibendum imperdiet tellus, sit amet tristique nunc tempus imperdiet. Proin laoreet elit in metus rhoncus placerat. Pellentesque ut maximus orci. Curabitur porttitor pellentesque maximus. Vivamus pretium orci tortor, sit amet feugiat risus sollicitudin sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam vel molestie libero. Donec leo turpis, posuere quis mattis ut, feugiat non elit. Praesent fermentum interdum tempor. Nulla finibus enim sed sapien volutpat ultrices. In consectetur dolor et maximus congue. Nunc ex turpis, viverra at ultrices et, egestas at velit. Praesent porttitor dictum metus non ultrices. Phasellus ut ultrices nisi. Cras venenatis lorem ut lorem commodo, ut congue augue posuere. Pellentesque facilisis leo sit amet metus semper scelerisque.

Sed massa lectus, tincidunt id ex sit amet, aliquet vehicula sapien. Nam pellentesque sem ut tincidunt interdum. Pellentesque condimentum fermentum augue, quis efficitur sem vulputate vitae. Phasellus sollicitudin vulputate sodales. Duis quis fermentum nulla. Cras blandit purus lorem, ut dictum dolor pharetra at. Morbi ut nunc eget sapien gravida malesuada. Donec et ex eget lorem volutpat blandit. Sed tincidunt eros vel mollis lacinia. Cras id consequat metus, sit amet lobortis tellus. Suspendisse nisi enim, imperdiet eget diam ac, egestas dictum est. Integer ornare justo ullamcorper velit convallis sagittis. Nunc in maximus diam, facilisis dictum velit.

Nulla porta libero est, non ultricies risus tempus nec. Maecenas quis dignissim nulla. Pellentesque quam eros, tempor ac lectus a, suscipit commodo tellus. Nullam enim ante, posuere quis metus vel, elementum aliquam nulla. In pharetra, lorem vitae faucibus elementum, nisi magna ornare nisi, sed congue dolor est ut massa. Donec vitae malesuada sem. Cras accumsan rhoncus purus, eu volutpat ex lacinia id. Phasellus efficitur at arcu ac tristique. Vestibulum blandit massa vel ex aliquam, quis suscipit tortor congue. Nullam porta sollicitudin dolor in placerat. Phasellus a ex vitae lacus tempor pulvinar. Aenean vel tortor blandit, sollicitudin dolor et, malesuada leo. Fusce eleifend metus et dui pretium vehicula. Phasellus cursus, ligula nec consectetur condimentum, arcu felis lobortis elit, sit amet rutrum tortor urna at augue. Ut at tortor eros. Morbi non pharetra ligula.

Etiam faucibus odio non viverra cursus. Sed ullamcorper interdum nulla, vitae tincidunt lacus congue ut. Nulla sed iaculis lorem. Mauris a gravida metus, nec faucibus leo. Duis eleifend turpis eros, et lobortis metus commodo eget. Etiam urna tortor, condimentum non nibh eu, lobortis vulputate urna. Morbi est arcu, vestibulum a semper auctor, convallis sed risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus sed faucibus dui. Vivamus pulvinar eleifend est, cursus sodales ligula consequat id. Quisque tristique in mi sit amet tempus. Donec in ex quis purus interdum viverra eu id nunc.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam congue condimentum neque, sit amet vulputate odio molestie ut. Sed rutrum enim vitae laoreet viverra. Nullam non tristique tortor. Mauris lacinia efficitur pretium. Quisque mattis dignissim erat, id faucibus eros viverra in. Fusce ut nibh ac sem tincidunt tincidunt. Etiam varius, eros eget accumsan gravida, ipsum nulla aliquam erat, ac euismod risus mi ac odio. Praesent nec iaculis nibh, ac dapibus purus. Morbi nulla felis, gravida vel fringilla sed, rhoncus non tortor. In turpis enim, porttitor sed congue id, suscipit id libero. Praesent convallis orci varius nisi maximus gravida. Sed a ante vel orci accumsan sollicitudin non in mi. Vivamus sem urna, imperdiet eget lorem nec, faucibus vestibulum lorem. Phasellus facilisis tellus et felis faucibus, a maximus ipsum sollicitudin. Suspendisse potenti.

Cras bibendum imperdiet tellus, sit amet tristique nunc tempus imperdiet. Proin laoreet elit in metus rhoncus placerat. Pellentesque ut maximus orci. Curabitur porttitor pellentesque maximus. Vivamus pretium orci tortor, sit amet feugiat risus sollicitudin sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam vel molestie libero. Donec leo turpis, posuere quis mattis ut, feugiat non elit. Praesent fermentum interdum tempor. Nulla finibus enim sed sapien volutpat ultrices. In consectetur dolor et maximus congue. Nunc ex turpis, viverra at ultrices et, egestas at velit. Praesent porttitor dictum metus non ultrices. Phasellus ut ultrices nisi. Cras venenatis lorem ut lorem commodo, ut congue augue posuere. Pellentesque facilisis leo sit amet metus semper scelerisque.

Sed massa lectus, tincidunt id ex sit amet, aliquet vehicula sapien. Nam pellentesque sem ut tincidunt interdum. Pellentesque condimentum fermentum augue, quis efficitur sem vulputate vitae. Phasellus sollicitudin vulputate sodales. Duis quis fermentum nulla. Cras blandit purus lorem, ut dictum dolor pharetra at. Morbi ut nunc eget sapien gravida malesuada. Donec et ex eget lorem volutpat blandit. Sed tincidunt eros vel mollis lacinia. Cras id consequat metus, sit amet lobortis tellus. Suspendisse nisi enim, imperdiet eget diam ac, egestas dictum est. Integer ornare justo ullamcorper velit convallis sagittis. Nunc in maximus diam, facilisis dictum velit.

Nulla porta libero est, non ultricies risus tempus nec. Maecenas quis dignissim nulla. Pellentesque quam eros, tempor ac lectus a, suscipit commodo tellus. Nullam enim ante, posuere quis metus vel, elementum aliquam nulla. In pharetra, lorem vitae faucibus elementum, nisi magna ornare nisi, sed congue dolor est ut massa. Donec vitae malesuada sem. Cras accumsan rhoncus purus, eu volutpat ex lacinia id. Phasellus efficitur at arcu ac tristique. Vestibulum blandit massa vel ex aliquam, quis suscipit tortor congue. Nullam porta sollicitudin dolor in placerat. Phasellus a ex vitae lacus tempor pulvinar. Aenean vel tortor blandit, sollicitudin dolor et, malesuada leo. Fusce eleifend metus et dui pretium vehicula. Phasellus cursus, ligula nec consectetur condimentum, arcu felis lobortis elit, sit amet rutrum tortor urna at augue. Ut at tortor eros. Morbi non pharetra ligula.

Etiam faucibus odio non viverra cursus. Sed ullamcorper interdum nulla, vitae tincidunt lacus congue ut. Nulla sed iaculis lorem. Mauris a gravida metus, nec faucibus leo. Duis eleifend turpis eros, et lobortis metus commodo eget. Etiam urna tortor, condimentum non nibh eu, lobortis vulputate urna. Morbi est arcu, vestibulum a semper auctor, convallis sed risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus sed faucibus dui. Vivamus pulvinar eleifend est, cursus sodales ligula consequat id. Quisque tristique in mi sit amet tempus. Donec in ex quis purus interdum viverra eu id nunc.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam congue condimentum neque, sit amet vulputate odio molestie ut. Sed rutrum enim vitae laoreet viverra. Nullam non tristique tortor. Mauris lacinia efficitur pretium. Quisque mattis dignissim erat, id faucibus eros viverra in. Fusce ut nibh ac sem tincidunt tincidunt. Etiam varius, eros eget accumsan gravida, ipsum nulla aliquam erat, ac euismod risus mi ac odio. Praesent nec iaculis nibh, ac dapibus purus. Morbi nulla felis, gravida vel fringilla sed, rhoncus non tortor. In turpis enim, porttitor sed congue id, suscipit id libero. Praesent convallis orci varius nisi maximus gravida. Sed a ante vel orci accumsan sollicitudin non in mi. Vivamus sem urna, imperdiet eget lorem nec, faucibus vestibulum lorem. Phasellus facilisis tellus et felis faucibus, a maximus ipsum sollicitudin. Suspendisse potenti.

Cras bibendum imperdiet tellus, sit amet tristique nunc tempus imperdiet. Proin laoreet elit in metus rhoncus placerat. Pellentesque ut maximus orci. Curabitur porttitor pellentesque maximus. Vivamus pretium orci tortor, sit amet feugiat risus sollicitudin sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam vel molestie libero. Donec leo turpis, posuere quis mattis ut, feugiat non elit. Praesent fermentum interdum tempor. Nulla finibus enim sed sapien volutpat ultrices. In consectetur dolor et maximus congue. Nunc ex turpis, viverra at ultrices et, egestas at velit. Praesent porttitor dictum metus non ultrices. Phasellus ut ultrices nisi. Cras venenatis lorem ut lorem commodo, ut congue augue posuere. Pellentesque facilisis leo sit amet metus semper scelerisque.

Sed massa lectus, tincidunt id ex sit amet, aliquet vehicula sapien. Nam pellentesque sem ut tincidunt interdum. Pellentesque condimentum fermentum augue, quis efficitur sem vulputate vitae. Phasellus sollicitudin vulputate sodales. Duis quis fermentum nulla. Cras blandit purus lorem, ut dictum dolor pharetra at. Morbi ut nunc eget sapien gravida malesuada. Donec et ex eget lorem volutpat blandit. Sed tincidunt eros vel mollis lacinia. Cras id consequat metus, sit amet lobortis tellus. Suspendisse nisi enim, imperdiet eget diam ac, egestas dictum est. Integer ornare justo ullamcorper velit convallis sagittis. Nunc in maximus diam, facilisis dictum velit.

Nulla porta libero est, non ultricies risus tempus nec. Maecenas quis dignissim nulla. Pellentesque quam eros, tempor ac lectus a, suscipit commodo tellus. Nullam enim ante, posuere quis metus vel, elementum aliquam nulla. In pharetra, lorem vitae faucibus elementum, nisi magna ornare nisi, sed congue dolor est ut massa. Donec vitae malesuada sem. Cras accumsan rhoncus purus, eu volutpat ex lacinia id. Phasellus efficitur at arcu ac tristique. Vestibulum blandit massa vel ex aliquam, quis suscipit tortor congue. Nullam porta sollicitudin dolor in placerat. Phasellus a ex vitae lacus tempor pulvinar. Aenean vel tortor blandit, sollicitudin dolor et, malesuada leo. Fusce eleifend metus et dui pretium vehicula. Phasellus cursus, ligula nec consectetur condimentum, arcu felis lobortis elit, sit amet rutrum tortor urna at augue. Ut at tortor eros. Morbi non pharetra ligula.

Etiam faucibus odio non viverra cursus. Sed ullamcorper interdum nulla, vitae tincidunt lacus congue ut. Nulla sed iaculis lorem. Mauris a gravida metus, nec faucibus leo. Duis eleifend turpis eros, et lobortis metus commodo eget. Etiam urna tortor, condimentum non nibh eu, lobortis vulputate urna. Morbi est arcu, vestibulum a semper auctor, convallis sed risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus sed faucibus dui. Vivamus pulvinar eleifend est, cursus sodales ligula consequat id. Quisque tristique in mi sit amet tempus. Donec in ex quis purus interdum viverra eu id nunc.`)

	orderReceipt.pdf.OutputFileAndClose("hello.pdf")
}
