// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/:id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Account"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.AccountUpdateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Account"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/account/:id/activate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/account/:id/disable": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/account/:id/password/change": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.ChangePasswordParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.ChangePasswordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/accounts": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Accounts"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.AccountCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Account"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/auth": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Account"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/custom-field/:id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Field"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.CustomFieldUpdateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.CustomField"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/custom-fields": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Field"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "custom_object",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.CustomFields"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Field"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.CustomFieldCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.CustomField"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/customer/:id": {
            "get": {
                "description": "meta value will be string or entities.FieldOption array",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "put": {
                "description": "Add the string meta by \"meta\": {\"meta1\": \"meta value\"}, multiple meta by \"meta\": {\"meta1\": \"optionId;optionId\"}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.CustomerUpdateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/customers": {
            "get": {
                "description": "meta value will be string or entities.FieldOption array",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "eq",
                            "like"
                        ],
                        "type": "string",
                        "description": " ",
                        "name": "search_mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Customers"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "description": "Add the string meta by \"meta\": {\"meta1\": \"meta value\"}, multiple meta by \"meta\": {\"meta1\": \"optionId;optionId\"}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.CustomerCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/permissions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Permissions"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/role/:id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.RoleUpdateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Role"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Roles"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.RoleCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Role"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        },
        "/setting/general": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Setting"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Settings"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Setting"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/managers.SettingSetParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/swagger.Settings"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIInternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Account": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_login": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/entities.Role"
                },
                "status": {
                    "type": "string",
                    "default": "Active",
                    "enum": [
                        "Active",
                        "Disable"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "entities.CustomField": {
            "type": "object",
            "properties": {
                "custom_object": {
                    "type": "string"
                },
                "field_name": {
                    "$ref": "#/definitions/entities.MultiLangText"
                },
                "field_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.FieldOption"
                    }
                },
                "field_type": {
                    "type": "string",
                    "enum": [
                        "string",
                        "multiple"
                    ]
                },
                "id": {
                    "type": "string"
                },
                "remarks": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "default": "Active",
                    "enum": [
                        "Active",
                        "Disable"
                    ]
                },
                "unique_key": {
                    "type": "string"
                }
            }
        },
        "entities.Customer": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "avg_month_income": {
                    "type": "string"
                },
                "bank_ac_name": {
                    "type": "string"
                },
                "bank_ac_number": {
                    "type": "string"
                },
                "birth": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collateral": {
                    "type": "string"
                },
                "collateral_value": {
                    "type": "string"
                },
                "debt_instalment_amount": {
                    "type": "string"
                },
                "debt_outstanding": {
                    "type": "string"
                },
                "debt_status": {
                    "type": "string"
                },
                "debt_type": {
                    "type": "string"
                },
                "dti": {
                    "type": "string"
                },
                "fb_name": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_no": {
                    "type": "string"
                },
                "ig_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "linkedin_name": {
                    "type": "string"
                },
                "loan_amount": {
                    "type": "string"
                },
                "loan_date": {
                    "type": "string"
                },
                "loan_instalment_amount": {
                    "type": "string"
                },
                "loan_tenor": {
                    "type": "string"
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Meta"
                    }
                },
                "office_address": {
                    "type": "string"
                },
                "order_date": {
                    "type": "string"
                },
                "other_name": {
                    "type": "string"
                },
                "phone1": {
                    "type": "string"
                },
                "phone2": {
                    "type": "string"
                },
                "phone3": {
                    "type": "string"
                },
                "remarks": {
                    "type": "string"
                },
                "residential_address_1": {
                    "type": "string"
                },
                "residential_address_2": {
                    "type": "string"
                },
                "residential_address_3": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "default": "Active",
                    "enum": [
                        "Active",
                        "Disable"
                    ]
                },
                "status_date": {
                    "type": "string"
                },
                "tax_id_number": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "weibo_name": {
                    "type": "string"
                }
            }
        },
        "entities.FieldOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/entities.MultiLangText"
                }
            }
        },
        "entities.Meta": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "val": {}
            }
        },
        "entities.MultiLangText": {
            "type": "object",
            "properties": {
                "ch": {
                    "type": "string"
                },
                "en": {
                    "type": "string"
                },
                "zh": {
                    "type": "string"
                }
            }
        },
        "entities.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "string",
                    "example": "ACCOUNT:U;CUSTOMER:U;ROLE:U"
                }
            }
        },
        "entities.Setting": {
            "type": "object",
            "properties": {
                "setting": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "managers.AccountCreateParam": {
            "type": "object",
            "required": [
                "display_name",
                "password",
                "role_id",
                "username"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "managers.AccountUpdateParam": {
            "type": "object",
            "required": [
                "display_name",
                "password",
                "role_id",
                "username"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "managers.ChangePasswordParam": {
            "type": "object",
            "properties": {
                "old_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "managers.CustomFieldCreateParam": {
            "type": "object",
            "properties": {
                "custom_object": {
                    "type": "string"
                },
                "field_name": {
                    "$ref": "#/definitions/managers.MultiLangText"
                },
                "field_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/managers.FieldOptionParam"
                    }
                },
                "field_type": {
                    "type": "string",
                    "enum": [
                        "string",
                        "multiple"
                    ]
                },
                "remarks": {
                    "type": "string"
                },
                "unique_key": {
                    "type": "string"
                }
            }
        },
        "managers.CustomFieldUpdateParam": {
            "type": "object",
            "properties": {
                "field_name": {
                    "$ref": "#/definitions/managers.MultiLangText"
                },
                "field_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/managers.FieldOptionUpdate"
                    }
                },
                "field_type": {
                    "type": "string",
                    "enum": [
                        "string",
                        "multiple"
                    ]
                },
                "remarks": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "Active",
                        "Disable"
                    ]
                },
                "unique_key": {
                    "type": "string"
                }
            }
        },
        "managers.CustomerCreateParam": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avg_month_income": {
                    "type": "string"
                },
                "bank_ac_name": {
                    "type": "string"
                },
                "bank_ac_number": {
                    "type": "string"
                },
                "birth": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collateral": {
                    "type": "string"
                },
                "collateral_value": {
                    "type": "string"
                },
                "debt_instalment_amount": {
                    "type": "string"
                },
                "debt_outstanding": {
                    "type": "string"
                },
                "debt_status": {
                    "type": "string"
                },
                "debt_type": {
                    "type": "string"
                },
                "dti": {
                    "type": "string"
                },
                "fb_name": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id_no": {
                    "type": "string"
                },
                "ig_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "linkedin_name": {
                    "type": "string"
                },
                "loan_amount": {
                    "type": "string"
                },
                "loan_date": {
                    "type": "string"
                },
                "loan_instalment_amount": {
                    "type": "string"
                },
                "loan_tenor": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "office_address": {
                    "type": "string"
                },
                "order_date": {
                    "type": "string"
                },
                "other_name": {
                    "type": "string"
                },
                "phone1": {
                    "type": "string"
                },
                "phone2": {
                    "type": "string"
                },
                "phone3": {
                    "type": "string"
                },
                "remarks": {
                    "type": "string"
                },
                "residential_address_1": {
                    "type": "string"
                },
                "residential_address_2": {
                    "type": "string"
                },
                "residential_address_3": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status_date": {
                    "type": "string"
                },
                "tax_id_number": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "weibo_name": {
                    "type": "string"
                }
            }
        },
        "managers.CustomerUpdateParam": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avg_month_income": {
                    "type": "string"
                },
                "bank_ac_name": {
                    "type": "string"
                },
                "bank_ac_number": {
                    "type": "string"
                },
                "birth": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collateral": {
                    "type": "string"
                },
                "collateral_value": {
                    "type": "string"
                },
                "debt_instalment_amount": {
                    "type": "string"
                },
                "debt_outstanding": {
                    "type": "string"
                },
                "debt_status": {
                    "type": "string"
                },
                "debt_type": {
                    "type": "string"
                },
                "dti": {
                    "type": "string"
                },
                "fb_name": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id_no": {
                    "type": "string"
                },
                "ig_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "linkedin_name": {
                    "type": "string"
                },
                "loan_amount": {
                    "type": "string"
                },
                "loan_date": {
                    "type": "string"
                },
                "loan_instalment_amount": {
                    "type": "string"
                },
                "loan_tenor": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "office_address": {
                    "type": "string"
                },
                "order_date": {
                    "type": "string"
                },
                "other_name": {
                    "type": "string"
                },
                "phone1": {
                    "type": "string"
                },
                "phone2": {
                    "type": "string"
                },
                "phone3": {
                    "type": "string"
                },
                "remarks": {
                    "type": "string"
                },
                "residential_address_1": {
                    "type": "string"
                },
                "residential_address_2": {
                    "type": "string"
                },
                "residential_address_3": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_date": {
                    "type": "string"
                },
                "tax_id_number": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "weibo_name": {
                    "type": "string"
                }
            }
        },
        "managers.FieldOptionParam": {
            "type": "object",
            "properties": {
                "name": {
                    "$ref": "#/definitions/managers.MultiLangText"
                }
            }
        },
        "managers.FieldOptionUpdate": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "CREATE",
                        "UPDATE",
                        "DELETE"
                    ]
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/managers.MultiLangText"
                }
            }
        },
        "managers.LoginParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "managers.MultiLangText": {
            "type": "object",
            "properties": {
                "ch": {
                    "type": "string"
                },
                "en": {
                    "type": "string"
                },
                "zh": {
                    "type": "string"
                }
            }
        },
        "managers.RoleCreateParam": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "string",
                    "example": "ACCOUNT:U;CUSTOMER:U;ROLE:U"
                }
            }
        },
        "managers.RoleUpdateParam": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "string",
                    "example": "ACCOUNT:U;CUSTOMER:U;ROLE:U"
                }
            }
        },
        "managers.SettingSetParam": {
            "type": "object",
            "additionalProperties": true
        },
        "swagger.APIForbiddenError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "swagger.APIInternalServerError": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "swagger.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "swagger.Account": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/entities.Account"
                }
            }
        },
        "swagger.AccountList": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Account"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "swagger.Accounts": {
            "type": "object",
            "properties": {
                "accounts": {
                    "$ref": "#/definitions/swagger.AccountList"
                }
            }
        },
        "swagger.AuthUser": {
            "type": "object",
            "properties": {
                "companyID": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/entities.Role"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "swagger.ChangePasswordResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "$ref": "#/definitions/swagger.Token"
                }
            }
        },
        "swagger.CustomField": {
            "type": "object",
            "properties": {
                "custom_field": {
                    "$ref": "#/definitions/entities.CustomField"
                }
            }
        },
        "swagger.CustomFieldList": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.CustomField"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "swagger.CustomFields": {
            "type": "object",
            "properties": {
                "custom_fields": {
                    "$ref": "#/definitions/swagger.CustomFieldList"
                }
            }
        },
        "swagger.Customer": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/entities.Customer"
                }
            }
        },
        "swagger.CustomerList": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Customer"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "swagger.Customers": {
            "type": "object",
            "properties": {
                "customers": {
                    "$ref": "#/definitions/swagger.CustomerList"
                }
            }
        },
        "swagger.LoginResponse": {
            "type": "object",
            "properties": {
                "authUser": {
                    "$ref": "#/definitions/swagger.AuthUser"
                },
                "token": {
                    "$ref": "#/definitions/swagger.Token"
                }
            }
        },
        "swagger.Permissions": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "swagger.Role": {
            "type": "object",
            "properties": {
                "role": {
                    "$ref": "#/definitions/entities.Role"
                }
            }
        },
        "swagger.RoleList": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Role"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "swagger.Roles": {
            "type": "object",
            "properties": {
                "roles": {
                    "$ref": "#/definitions/swagger.RoleList"
                }
            }
        },
        "swagger.SettingList": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Setting"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "swagger.Settings": {
            "type": "object",
            "properties": {
                "settings": {
                    "$ref": "#/definitions/swagger.SettingList"
                }
            }
        },
        "swagger.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
